const path = require('path');
const ShoppingList = require('../src/ShoppingList.js');
const Recipe = require('../src/Recipe.js');
const Ingredient = require('../src/Ingredient.js');
const Item = require('../src/Item.js');
const Day = require('../src/Day.js');
const Trip = require('../src/Trip.js');

// var butterItem = new Item();
// butterItem.setItemName('butter');
// butterItem.setDepartment('Dairy');
// var garlicPowderItem = new Item();
// garlicPowderItem.setItemName('garlic powder');
// garlicPowderItem.setDepartment('Spices/Oils');
// var rosemaryItem = new Item();
// rosemaryItem.setItemName('rosemary');
// rosemaryItem.setDepartment('Spices/Oils');
// var saltItem = new Item();
// saltItem.setItemName('salt');
// saltItem.setDepartment('Spices/Oils');
// var pepperItem = new Item();
// pepperItem.setItemName('pepper');
// pepperItem .setDepartment('Spices/Oils');
// var honeyItem = new Item();
// honeyItem.setItemName('honey');
// honeyItem.setDepartment('Condiments/Dressings');
// var chickenThighsItem = new Item();
// chickenThighsItem.setItemName('chicken thighs');
// chickenThighsItem.setDepartment('Meat/Protein');
// var wholeChickenItem = new Item();
// wholeChickenItem.setItemName('whole chicken');
// wholeChickenItem.setDepartment('Meat/Protein');
// var soySauceItem = new Item();
// soySauceItem.setItemName('soy sauce');
// soySauceItem.setDepartment('Condiments/Dressings');
// var orangeJuiceItem = new Item();
// orangeJuiceItem.setItemName('orange juice');
// orangeJuiceItem.setDepartment('Drinks');
// var garlicClovesItem = new Item();
// garlicClovesItem.setItemName('garlic cloves');
// garlicClovesItem.setDepartment('Spices/Oils');
// var oreganoItem = new Item();
// oreganoItem.setItemName('dried oregano');
// oreganoItem.setDepartment('Spices/Oils');
// var paprikaItem = new Item();
// paprikaItem.setItemName('paprika');
// paprikaItem.setDepartment('Spices/Oils');
// var flourItem = new Item();
// flourItem.setItemName('all-purpose flour');
// flourItem.setDepartment('Misc');
// var bakingPowderItem = new Item();
// bakingPowderItem.setItemName('baking powder');
// bakingPowderItem.setDepartment('Spices/Oils');
// var bakingSodaItem = new Item();
// bakingSodaItem.setItemName('baking soda');
// bakingSodaItem.setDepartment('Spices/Oils');
// var brownSugarItem = new Item();
// brownSugarItem.setItemName('brown sugar');
// brownSugarItem.setDepartment('Spices/Oils');
// var sourCreamItem = new Item();
// sourCreamItem.setItemName('sour cream');
// sourCreamItem.setDepartment('Dairy');
// var eggItem = new Item();
// eggItem.setItemName('egg');
// eggItem.setDepartment('Meat/Protein');
// var vanillaItem = new Item();
// vanillaItem.setItemName('vanilla extract');
// vanillaItem.setDepartment('Spices/Oils');
// var rhubarbItem = new Item();
// rhubarbItem.setItemName('rhubarb');
// rhubarbItem.setDepartment('Produce');
// var sugarItem = new Item();
// sugarItem.setItemName('sugar');
// sugarItem.setDepartment('Spices/Oils');
// var cinnamonItem = new Item();
// cinnamonItem.setItemName('cinnamon');
// cinnamonItem.setDepartment('Spices/Oils');
// var milkItem = new Item();
// milkItem.setItemName('milk');
// milkItem.setDepartment('Dairy');
// var parmesanCheeseItem = new Item();
// parmesanCheeseItem.setItemName('parmesan cheese');
// parmesanCheeseItem.setDepartment('Dairy');
// var lemonZestItem = new Item();
// lemonZestItem.setItemName('lemon zest');
// lemonZestItem.setDepartment('Produce');
// var cayennePepperItem = new Item();
// cayennePepperItem.setItemName('cayenne pepper');
// cayennePepperItem.setDepartment('Spices/Oils');
// var oliveOilItem = new Item();
// oliveOilItem.setItemName('olive oil');
// oliveOilItem.setDepartment('Spices/Oils');
// var baconItem = new Item();
// baconItem.setItemName('bacon');
// baconItem.setDepartment('Meat/Protein');
// var asparagusItem = new Item();
// asparagusItem.setItemName('asparagus');
// asparagusItem.setDepartment('Produce');
// var waterItem = new Item();
// waterItem.setItemName('water');
// waterItem.setDepartment('Drinks');
// var lentilsItem = new Item();
// lentilsItem.setItemName('lentils');
// lentilsItem.setDepartment('Grains');
// var romaTomatoItem = new Item();
// romaTomatoItem.setItemName('roma tomato');
// romaTomatoItem.setDepartment('Produce');
// var redOnionItem = new Item();
// redOnionItem.setItemName('red onion');
// redOnionItem.setDepartment('Produce');
// var greenBellPepperItem = new Item();
// greenBellPepperItem.setItemName('green bell pepper');
// greenBellPepperItem.setDepartment('Produce');
// var greenChilePepperItem = new Item();
// greenChilePepperItem.setItemName('green chile pepper');
// greenChilePepperItem.setDepartment('Produce');
// var lemonItem = new Item();
// lemonItem.setItemName('lemon');
// lemonItem.setDepartment('Produce');
// var carrotItem = new Item();
// carrotItem.setItemName('carrot');
// carrotItem.setDepartment('Produce');
// var olivesItem = new Item();
// olivesItem.setItemName('black olives');
// olivesItem.setDepartment('Canned Goods');
// var cilantroItem = new Item();
// cilantroItem.setItemName('cilantro');
// cilantroItem.setDepartment('Produce');
// var whiteBreadItem = new Item();
// whiteBreadItem.setItemName('white bread');
// whiteBreadItem.setDepartment('Grains');
// var tomatoItem = new Item();
// tomatoItem.setItemName('tomato');
// tomatoItem.setDepartment('Produce');
//
// var HoneyGarlicChickenRosemary = new Recipe();
// var butter = new Ingredient();
// butter.setAmount(3);
// butter.setDescriptor('tbs');
// butter.setItem(butterItem);
// var garlicPowder = new Ingredient();
// garlicPowder.setAmount(1.5);
// garlicPowder.setDescriptor('tbs');
// garlicPowder.setItem(garlicPowderItem);
// var rosemary = new Ingredient();
// rosemary.setAmount(2);
// rosemary.setDescriptor('tsp');
// rosemary.setItem(rosemaryItem);
// var salt = new Ingredient();
// salt.setAmount(1);
// salt.setDescriptor('tsp');
// salt.setItem(saltItem);
// var pepper = new Ingredient();
// pepper.setAmount(1);
// pepper.setDescriptor('tsp');
// pepper.setItem(pepperItem);
// var honey = new Ingredient();
// honey.setAmount(.5);
// honey.setDescriptor('cup');
// honey.setItem(honeyItem);
// var chickenThighs = new Ingredient();
// chickenThighs.setAmount(6);
// chickenThighs.setDescriptor('each');
// chickenThighs.setItem(chickenThighsItem);
// HoneyGarlicChickenRosemary.setServings(1);
// HoneyGarlicChickenRosemary.addIngredient(butter);
// HoneyGarlicChickenRosemary.addIngredient(garlicPowder);
// HoneyGarlicChickenRosemary.addIngredient(rosemary);
// HoneyGarlicChickenRosemary.addIngredient(salt);
// HoneyGarlicChickenRosemary.addIngredient(pepper);
// HoneyGarlicChickenRosemary.addIngredient(honey);
// HoneyGarlicChickenRosemary.addIngredient(chickenThighs);
//
// var OrangeHoneyGarlicChicken = new Recipe();
// var wholeChicken = new Ingredient();
// wholeChicken.setAmount(1);
// wholeChicken.setDescriptor('each');
// wholeChicken.setItem(wholeChickenItem);
// var soySauce = new Ingredient();
// soySauce.setAmount(3);
// soySauce.setDescriptor('tbs');
// soySauce.setItem(soySauceItem);
// honey.setAmount(2);
// honey.setDescriptor('tbs');
// var orangeJuice = new Ingredient();
// orangeJuice.setAmount(.25);
// orangeJuice.setDescriptor('cup');
// orangeJuice.setItem(orangeJuiceItem);
// var garlicCloves = new Ingredient();
// garlicCloves.setAmount(2);
// garlicCloves.setDescriptor('each');
// garlicCloves.setItem(garlicClovesItem);
// var oregano = new Ingredient();
// oregano.setAmount(.5);
// oregano.setDescriptor('tsp');
// oregano.setItem(oreganoItem);
// pepper.setAmount(.25);
// var paprika = new Ingredient();
// paprika.setAmount(.5);
// paprika.setDescriptor('tsp');
// paprika.setItem(paprikaItem);
// OrangeHoneyGarlicChicken.setServings(1);
// OrangeHoneyGarlicChicken.addIngredient(wholeChicken);
// OrangeHoneyGarlicChicken.addIngredient(soySauce);
// OrangeHoneyGarlicChicken.addIngredient(honey);
// OrangeHoneyGarlicChicken.addIngredient(orangeJuice);
// OrangeHoneyGarlicChicken.addIngredient(garlicCloves);
// OrangeHoneyGarlicChicken.addIngredient(oregano);
// OrangeHoneyGarlicChicken.addIngredient(pepper);
// OrangeHoneyGarlicChicken.addIngredient(paprika);
//
// var TomatoBaconGrilledCheese = new Recipe();
// var bacon = new Ingredient();
// bacon.setAmount(8);
// bacon.setDescriptor('slices');
// bacon.setItem(baconItem);
// butter.setAmount(.25);
// butter.setDescriptor('cup');
// var whiteBread = new Ingredient();
// whiteBread.setAmount(8);
// whiteBread.setDescriptor('slices');
// whiteBread.setItem(whiteBreadItem);
// var tomato = new Ingredient();
// tomato.setAmount(8);
// tomato.setDescriptor('slices');
// tomato.setItem(tomatoItem);
// TomatoBaconGrilledCheese.setServings(1);
// TomatoBaconGrilledCheese.addIngredient(bacon);
// TomatoBaconGrilledCheese.addIngredient(butter);
// TomatoBaconGrilledCheese.addIngredient(whiteBread);
// TomatoBaconGrilledCheese.addIngredient(tomato);

var item = new Item();
item.setItemName('butter');
item.setDepartment('Dairy');
var ingredient = new Ingredient();
ingredient.setAmount(1);
ingredient.setDescriptor('cup');
ingredient.setItem(item);
var recipe = new Recipe();
recipe.addIngredient(ingredient);
recipe.setServings(1);
var recipe1 = new Recipe();
var ingredient1 = new Ingredient();
ingredient1.setAmount(.5);
ingredient1.setDescriptor('cup');
ingredient1.setItem(item);
recipe1.addIngredient(ingredient1);
recipe1.setServings(4);
var ingredient2 = new Ingredient();
ingredient2.setAmount(1);
ingredient2.setDescriptor('each');
ingredient2.setItem(item);
recipe1.addIngredient(ingredient2);
var ingredient3 = new Ingredient();
ingredient3.setAmount(2);
ingredient3.setDescriptor('oz');
ingredient3.setItem(item);
recipe.addIngredient(ingredient3);
var ingredient4 = new Ingredient();
ingredient4.setAmount(1);
ingredient4.setDescriptor('lb');
ingredient4.setItem(item);
recipe1.addIngredient(ingredient4);
var ingredient5 = new Ingredient();
ingredient5.setAmount(2);
ingredient5.setDescriptor('tsp');
ingredient5.setItem(item);
recipe1.addIngredient(ingredient5);

var item2 = new Item();
item2.setItemName('penne pasta');
item2.setDepartment('Bread/Pasta/Grains');
var item3 = new Item();
item3.setItemName('strawberry');
item3.setDepartment('Produce');
var item4 = new Item();
item4.setItemName('steak');
item4.setDepartment('Meat/Protein');
var item5 = new Item();
item5.setItemName('frozen corn');
item5.setDepartment('Packaged/Frozen');
var item6 = new Item();
item6.setItemName('paprika');
item6.setDepartment('Spices/Oils');
var item7 = new Item();
item7.setItemName('ketchup');
item7.setDepartment('Condiments/Dressings');
var item8 = new Item();
item8.setItemName('pineapple');
item8.setDepartment('Canned');

var ingredient12 = new Ingredient();
ingredient12.setItem(item2);
ingredient12.setAmount(16);
ingredient12.setDescriptor('oz');
var ingredient13 = new Ingredient();
ingredient13.setItem(item3);
ingredient13.setAmount(2);
ingredient13.setDescriptor('cup');
var ingredient14 = new Ingredient();
ingredient14.setItem(item4);
ingredient14.setAmount(12);
ingredient14.setDescriptor('oz');
var ingredient15 = new Ingredient();
ingredient15.setItem(item5);
ingredient15.setAmount(1);
ingredient15.setDescriptor('each');
var ingredient16 = new Ingredient();
ingredient16.setItem(item6);
ingredient16.setAmount(3);
ingredient16.setDescriptor('tbs');
var ingredient17 = new Ingredient();
ingredient17.setItem(item7);
ingredient17.setAmount(2);
ingredient17.setDescriptor('fl-oz');
var ingredient18 = new Ingredient();
ingredient18.setItem(item8);
ingredient18.setAmount(14.5);
ingredient18.setDescriptor('oz');

var recipe2 = new Recipe();
recipe2.setServings(4);
recipe2.addIngredient(ingredient12);
recipe2.addIngredient(ingredient13);
recipe2.addIngredient(ingredient14);
recipe2.addIngredient(ingredient15);
recipe2.addIngredient(ingredient16);
recipe2.addIngredient(ingredient17);
recipe2.addIngredient(ingredient18);
recipe2.addIngredient(ingredient12);
recipe2.addIngredient(ingredient13);
recipe2.addIngredient(ingredient14);
recipe2.addIngredient(ingredient15);
recipe2.addIngredient(ingredient16);
recipe2.addIngredient(ingredient17);
recipe2.addIngredient(ingredient18);
recipe.setName('Delicious Dinner');
recipe1.setName('Yummy Breakfast');
recipe2.setName('Super Good Lunch');

var day = new Day();
day.setBreakfast(recipe1);
day.setLunch(recipe2);
day.setDinner(recipe);

var trip = new Trip();
trip.addDay(day);
trip.setHeadCount(4);
trip.setTripName('Test Trip 1');
trip.setDate('4/10/2018');


var shoppingList = new ShoppingList();
shoppingList.createShppingList(trip);
shoppingList.print(trip, 'testPdf.pdf');
